name: build

on:
  push:
    branches:
      - main

env:
  GHCR_IMAGE: ghcr.io/vegidio/countries

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip-ci]') && !contains(github.event.head_commit.message, '👀')"
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set variables
        id: vars
        run: |
          echo "IMAGE_VERSION=$(date +'%y.%-m.%-d')" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build -t $GHCR_IMAGE -t $ECR_IMAGE . --build-arg VERSION=${{ env.IMAGE_VERSION }}

      - name: Login to Github CR
        run: |
          echo "${{ secrets.GHCR_PASSWORD }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Push to Github registry
        run: |
          docker tag $GHCR_IMAGE:latest $GHCR_IMAGE:${{ env.IMAGE_VERSION }}
          docker push $GHCR_IMAGE:latest
          docker push $GHCR_IMAGE:${{ env.IMAGE_VERSION }}
