name: build

on:
  push:
    branches:
      - master

env:
  GHCR_IMAGE: ghcr.io/vegidio/countries
  ECR_IMAGE: 318715067340.dkr.ecr.eu-north-1.amazonaws.com/countries

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip-ci]') && !contains(github.event.head_commit.message, '👀')"
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set variables
        id: vars
        run: |
          echo "IMAGE_VERSION=$(date +'%y.%-m.%-d')" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build -t $GHCR_IMAGE -t $ECR_IMAGE . --build-arg VERSION=${{ env.IMAGE_VERSION }}

      - name: Login to Github CR
        run: |
          echo "${{ secrets.GHCR_PASSWORD }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Push to Github registry
        run: |
          docker tag $GHCR_IMAGE:latest $GHCR_IMAGE:${{ env.IMAGE_VERSION }}
          docker push $GHCR_IMAGE:latest
          docker push $GHCR_IMAGE:${{ env.IMAGE_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_AC_ID }}
          aws-secret-access-key: ${{ secrets.AWS_AC_SECRET }}
          aws-region: eu-north-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push to AWS registry
        run: |
          docker tag $ECR_IMAGE:latest $ECR_IMAGE:${{ env.IMAGE_VERSION }}
          docker push $ECR_IMAGE:latest
          docker push $ECR_IMAGE:${{ env.IMAGE_VERSION }}
